// slug util (auto-generated from galleryCharacters.json)

const ELEMENT_BY_SLUG = {
  'albedo': 'geo',
  'alhaitham': 'dendro',
  'amber': 'pyro',
  'arataki-itto': 'geo',
  'arlecchino': 'pyro',
  'baizhu': 'dendro',
  'barbara': 'hydro',
  'beidou': 'electro',
  'bennett': 'pyro',
  'candace': 'hydro',
  'charlotte': 'cryo',
  'chasca': 'anemo',
  'chevreuse': 'pyro',
  'chiori': 'geo',
  'chongyun': 'cryo',
  'citlali': 'cryo',
  'clorinde': 'electro',
  'collei': 'dendro',
  'cyno': 'electro',
  'dehya': 'pyro',
  'diluc': 'pyro',
  'diona': 'cryo',
  'dori': 'electro',
  'emilie': 'dendro',
  'eula': 'cryo',
  'faruzan': 'anemo',
  'fischl': 'electro',
  'freminet': 'cryo',
  'furina': 'hydro',
  'ganyu': 'cryo',
  'gorou': 'geo',
  'hu-tao': 'pyro',
  'jean': 'anemo',
  'kaedehara-kazuha': 'anemo',
  'kaeya': 'cryo',
  'kamisato-ayaka': 'cryo',
  'kamisato-ayato': 'hydro',
  'kaveh': 'dendro',
  'keqing': 'electro',
  'kinich': 'dendro',
  'kirara': 'dendro',
  'klee': 'pyro',
  'kujou-sara': 'electro',
  'kuki-shinobu': 'electro',
  'lan-yan': 'hydro',
  'layla': 'cryo',
  'lisa': 'electro',
  'lynette': 'hydro',
  'lyney': 'pyro',
  'mavuika': 'pyro',
  'mika': 'hydro',
  'mona': 'hydro',
  'mualani': 'hydro',
  'nahida': 'dendro',
  'navia': 'geo',
  'neuvillette': 'hydro',
  'nilou': 'hydro',
  'ningguang': 'geo',
  'noelle': 'geo',
  'ororon': 'electro',
  'qiqi': 'cryo',
  'raiden-shogun': 'electro',
  'razor': 'electro',
  'rosaria': 'cryo',
  'sangonomiya-kokomi': 'hydro',
  'sayu': 'anemo',
  'sethos': 'dendro',
  'shenhe': 'cryo',
  'shikanoin-heizou': 'anemo',
  'sigewinne': 'hydro',
  'skirk': 'cryo',
  'sucrose': 'anemo',
  'tartaglia': 'hydro',
  'thoma': 'pyro',
  'tighnari': 'dendro',
  'varesa': 'electro',
  'venti': 'anemo',
  'wanderer': 'anemo',
  'wriothesley': 'cryo',
  'xiangling': 'pyro',
  'xianyun': 'anemo',
  'xiao': 'anemo',
  'xilonen': 'geo',
  'xingqiu': 'hydro',
  'xinyan': 'pyro',
  'yae-miko': 'electro',
  'yanfei': 'pyro',
  'yaoyao': 'dendro',
  'yelan': 'hydro',
  'yoimiya': 'pyro',
  'yumemizuki-mizuki': 'anemo',
  'yun-jin': 'geo',
  'zhongli': 'geo',
  
  'shogun': 'electro',
}

const NAME_BY_SLUG = {
  'albedo': 'Albedo',
  'alhaitham': 'Alhaitham',
  'amber': 'Amber',
  'arataki-itto': 'Arataki Itto',
  'arlecchino': 'Arlecchino',
  'baizhu': 'Baizhu',
  'barbara': 'Barbara',
  'beidou': 'Beidou',
  'bennett': 'Bennett',
  'candace': 'Candace',
  'charlotte': 'Charlotte',
  'chasca': 'Chasca',
  'chevreuse': 'Chevreuse',
  'chiori': 'Chiori',
  'chongyun': 'Chongyun',
  'citlali': 'Citlali',
  'clorinde': 'Clorinde',
  'collei': 'Collei',
  'cyno': 'Cyno',
  'dehya': 'Dehya',
  'diluc': 'Diluc',
  'diona': 'Diona',
  'dori': 'Dori',
  'emilie': 'Emilie',
  'eula': 'Eula',
  'faruzan': 'Faruzan',
  'fischl': 'Fischl',
  'freminet': 'Freminet',
  'furina': 'Furina',
  'ganyu': 'Ganyu',
  'gorou': 'Gorou',
  'hu-tao': 'Hu Tao',
  'jean': 'Jean',
  'kaedehara-kazuha': 'Kaedehara Kazuha',
  'kaeya': 'Kaeya',
  'kamisato-ayaka': 'Kamisato Ayaka',
  'kamisato-ayato': 'Kamisato Ayato',
  'kaveh': 'Kaveh',
  'keqing': 'Keqing',
  'kinich': 'Kinich',
  'kirara': 'Kirara',
  'klee': 'Klee',
  'kujou-sara': 'Kujou Sara',
  'kuki-shinobu': 'Kuki Shinobu',
  'lan-yan': 'Lan Yan',
  'layla': 'Layla',
  'lisa': 'Lisa',
  'lynette': 'Lynette',
  'lyney': 'Lyney',
  'mavuika': 'Mavuika',
  'mika': 'Mika',
  'mona': 'Mona',
  'mualani': 'Mualani',
  'nahida': 'Nahida',
  'navia': 'Navia',
  'neuvillette': 'Neuvillette',
  'nilou': 'Nilou',
  'ningguang': 'Ningguang',
  'noelle': 'Noelle',
  'ororon': 'Ororon',
  'qiqi': 'Qiqi',
  'raiden-shogun': 'Raiden Shogun',
  'razor': 'Razor',
  'rosaria': 'Rosaria',
  'sangonomiya-kokomi': 'Sangonomiya Kokomi',
  'sayu': 'Sayu',
  'sethos': 'Sethos',
  'shenhe': 'Shenhe',
  'shikanoin-heizou': 'Shikanoin Heizou',
  'sigewinne': 'Sigewinne',
  'skirk': 'Skirk',
  'sucrose': 'Sucrose',
  'tartaglia': 'Tartaglia',
  'thoma': 'Thoma',
  'tighnari': 'Tighnari',
  'varesa': 'Varesa',
  'venti': 'Venti',
  'wanderer': 'Wanderer',
  'wriothesley': 'Wriothesley',
  'xiangling': 'Xiangling',
  'xianyun': 'Xianyun',
  'xiao': 'Xiao',
  'xilonen': 'Xilonen',
  'xingqiu': 'Xingqiu',
  'xinyan': 'Xinyan',
  'yae-miko': 'Yae-miko',
  'yanfei': 'Yanfei',
  'yaoyao': 'Yaoyao',
  'yelan': 'Yelan',
  'yoimiya': 'Yoimiya',
  'yumemizuki-mizuki': 'Yumemizuki Mizuki',
  'yun-jin': 'Yun Jin',
  'zhongli': 'Zhongli',
 
  'shogun': 'Raiden Shogun',
}

export function getCharacterMetaFromSlug(slug) {
  const element = ELEMENT_BY_SLUG[slug] || 'pyro'
  const name = NAME_BY_SLUG[slug] || slug.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
  return { name, element }
}
